version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/api'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '06:00'
      timezone: 'America/Sao_Paulo'
    open-pull-requests-limit: 10
    labels:
      - 'api'
    groups:
      dependencies:
        patterns:
          - '*'

  - package-ecosystem: 'npm'
    directory: '/app'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '06:00'
      timezone: 'America/Sao_Paulo'
    open-pull-requests-limit: 10
    labels:
      - 'app'
    groups:
      dependencies:
        patterns:
          - '*'

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '06:00'
      timezone: 'America/Sao_Paulo'
    open-pull-requests-limit: 10
    labels:
      - 'root'
    groups:
      dependencies:
        patterns:
          - '*'

  - package-ecosystem: 'docker'
    directory: '/.docker/api'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '06:00'
      timezone: 'America/Sao_Paulo'
    labels:
      - 'docker'
    groups:
      docker:
        patterns:
          - '*'

  - package-ecosystem: 'docker'
    directory: '/.docker/app'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '06:00'
      timezone: 'America/Sao_Paulo'
    labels:
      - 'docker'
    groups:
      docker:
        patterns:
          - '*'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '06:00'
      timezone: 'America/Sao_Paulo'
    groups:
      actions:
        patterns:
          - '*'
