import { isOnline, enqueueMutation, type QueuedMutationMethod } from '../utils/offlineQueue';

const BASE = '/api/v1';

const WRITE_METHODS: QueuedMutationMethod[] = ['POST', 'PATCH', 'PUT', 'DELETE'];

function getCookie(name: string): string | undefined {
  const match = document.cookie.match(new RegExp(`(?:^|;\\s*)${name}=([^;]*)`));
  return match?.[1];
}

function extractIdFromPath(path: string): string | undefined {
  // Routes here are always `/<collection>/<id>[/<action>]` (e.g. /tasks/:id,
  // /tasks/:id/complete, /habits/:id/completions) - the id is always the
  // second segment, never the last one (actions/sub-resources can follow it).
  const segments = path.split('/').filter(Boolean);
  return segments[1];
}

// Builds a same-shape stand-in for the REST response while offline, so
// callers (and `runOptimistic()`'s 2000ms budget) get something to work with
// immediately instead of waiting on a network call that will never resolve.
// The queued mutation itself carries the real request; once it replays
// successfully the normal publishEvent() -> Redis -> Socket.IO -> useSync
// flow is what actually reconciles state - this synthetic value is only a
// placeholder for the immediate call site, never a source of truth.
function buildSyntheticResponse<T>(
  method: QueuedMutationMethod,
  path: string,
  init: RequestInit,
  clientEntityId?: string,
): T {
  if (method === 'DELETE') {
    return undefined as T;
  }

  const parsedBody = init.body ? JSON.parse(init.body as string) : {};

  if (method === 'POST') {
    // Creation calls (e.g. POST /tasks) have no id in the path - use the
    // client-minted id generated by the caller (see `request()`) so the
    // same id is both returned here and stored on the queued mutation record
    // for later remapping once the real server id is known. Action calls on
    // an existing resource (e.g. POST /tasks/:id/complete) do have one
    // embedded in the path - reuse it instead of minting a new, unrelated id
    // that would desync from the record actually being acted on.
    return { id: parsedBody.id ?? extractIdFromPath(path) ?? clientEntityId ?? crypto.randomUUID(), ...parsedBody } as T;
  }

  // PATCH / PUT: echo the id embedded in the path plus whatever the caller
  // sent, so e.g. apiUpdateTask('/tasks/:id', patch) gets { id, ...patch }.
  const id = extractIdFromPath(path);
  return { ...(id ? { id } : {}), ...parsedBody } as T;
}

async function request<T>(path: string, init: RequestInit = {}): Promise<T> {
  const method = (init.method ?? 'GET').toUpperCase() as QueuedMutationMethod;

  // Auth endpoints are never queued: logging in/out/registering requires a
  // real round trip and must fail loudly when offline, not resolve with a
  // synthetic session. Everything else that mutates app data is deferred.
  if (!path.startsWith('/auth/') && WRITE_METHODS.includes(method) && !isOnline()) {
    // Create calls (POST with no id segment in the path) mint their id here,
    // once, so the same value is both stored on the queued record (as
    // `clientEntityId`, for later remapping - see offlineQueue.remapQueuedId)
    // and returned in the synthetic response. Previously this id was
    // generated independently inside buildSyntheticResponse and never
    // persisted, so a dependent mutation queued afterwards (e.g. completing
    // or deleting the just-created record while still offline) had no way to
    // be corrected once the real server-assigned id came back from replay.
    const isCreate = method === 'POST' && !extractIdFromPath(path);
    const clientEntityId = isCreate ? crypto.randomUUID() : undefined;
    await enqueueMutation({ method, path, body: (init.body as string) ?? '', clientEntityId });
    return buildSyntheticResponse<T>(method, path, init, clientEntityId);
  }

  const xsrfToken = getCookie('XSRF-TOKEN');
  const headers: Record<string, string> = {
    'Content-Type': 'application/json',
    ...(init.headers as Record<string, string> ?? {}),
  };
  if (xsrfToken) {
    headers['X-XSRF-TOKEN'] = xsrfToken;
  }

  const res = await fetch(`${BASE}${path}`, {
    ...init,
    headers,
    credentials: 'include',
  });
  if (!res.ok) {
    const body = await res.json().catch(() => ({}));
    throw new Error(body?.error?.message ?? `HTTP ${res.status}`);
  }
  return res.json() as Promise<T>;
}

export { request };

// ── Auth ─────────────────────────────────────────────────────────────────────

export interface AuthUser {
  id: string;
  email: string;
  displayName: string;
}

export async function apiRegister(email: string, password: string, displayName: string): Promise<AuthUser> {
  const data = await request<{ user: AuthUser; token: string }>('/auth/register', {
    method: 'POST',
    body: JSON.stringify({ email, password, displayName }),
  });
  return data.user;
}

export async function apiLogin(email: string, password: string): Promise<AuthUser> {
  const data = await request<{ user: AuthUser; token: string }>('/auth/login', {
    method: 'POST',
    body: JSON.stringify({ email, password }),
  });
  return data.user;
}

export async function apiLogout(): Promise<void> {
  await request<{ success: boolean }>('/auth/logout', { method: 'POST' });
}

// ── Tasks ─────────────────────────────────────────────────────────────────────

export interface ApiTask {
  id: string;
  title: string;
  description?: string;
  priority: number;
  projectId: string;
  sectionId?: string;
  parentTaskId?: string;
  dueDate?: string;
  isCompleted: boolean;
  orderValue: number;
  depth?: number;
  type: 'task' | 'note';
  createdAt?: string;
}

export interface Preferences {
  userId: string;
  timeZone: string;
  weekStart: 'sunday' | 'monday';
  theme: 'light' | 'dark' | 'system';
  notificationsEnabled: boolean;
  font: 'lora' | 'playpen' | 'hubballi';
  showDots: boolean;
  background: 'beige' | 'white';
  smallCaps: boolean;
}

export async function fetchInboxTasks(): Promise<{ tasks: ApiTask[]; projectId: string | null }> {
  return request('/views/inbox');
}

export async function fetchTodayTasks(): Promise<{ overdue: ApiTask[]; today: ApiTask[] }> {
  return request('/views/today');
}

export async function fetchUpcomingTasks(): Promise<Array<{ date: string; tasks: ApiTask[] }>> {
  return request('/views/upcoming');
}

export async function fetchMonthNotes(year: number, month: number): Promise<{
  notesByDate: Record<string, ApiTask[]>;
  year: number;
  month: number;
}> {
  return request(`/views/month?year=${year}&month=${month}`);
}

export async function fetchPreferences(): Promise<Preferences> {
  return request<Preferences>('/preferences');
}

export async function apiUpdatePreferences(patch: Partial<Preferences>): Promise<Preferences> {
  return request<Preferences>('/preferences', {
    method: 'PATCH',
    body: JSON.stringify(patch),
  });
}

export async function apiCreateTask(input: {
  title: string;
  priority?: number;
  projectId?: string;
  dueDate?: string;
  parentTaskId?: string;
  depth?: number;
  type?: 'task' | 'note';
}): Promise<ApiTask> {
  return request<ApiTask>('/tasks', {
    method: 'POST',
    body: JSON.stringify(input),
  });
}

export async function apiUpdateTask(
  id: string,
  updates: Partial<Pick<ApiTask, 'title' | 'priority' | 'dueDate' | 'depth' | 'type'>> & {
    parentTaskId?: string | null;
  },
): Promise<ApiTask> {
  return request<ApiTask>(`/tasks/${id}`, {
    method: 'PATCH',
    body: JSON.stringify(updates),
  });
}

export async function apiToggleTask(id: string, isCompleted: boolean): Promise<ApiTask> {
  return request<ApiTask>(`/tasks/${id}/${isCompleted ? 'complete' : 'reopen'}`, {
    method: 'POST',
  });
}

export async function apiDeleteTask(id: string): Promise<void> {
  await request<unknown>(`/tasks/${id}`, { method: 'DELETE' });
}

// ── Projects ────────────────────────────────────────────────────────────────

export interface ApiProject {
  id: string;
  userId: string;
  parentId: string | null;
  name: string;
  color: string;
  isInbox: boolean;
  isArchived: boolean;
  orderValue: number;
  createdAt: string;
  updatedAt: string;
}

export const PROJECT_COLORS: ReadonlyArray<{ name: string; hex: string }> = [
  { name: 'berry_red', hex: '#b8255f' },
  { name: 'red', hex: '#db4035' },
  { name: 'orange', hex: '#ff9933' },
  { name: 'yellow', hex: '#fad000' },
  { name: 'olive_green', hex: '#afb83b' },
  { name: 'lime_green', hex: '#7ecc49' },
  { name: 'green', hex: '#299438' },
  { name: 'mint_green', hex: '#6accbc' },
  { name: 'teal', hex: '#158fad' },
  { name: 'sky_blue', hex: '#14aaf5' },
  { name: 'light_blue', hex: '#96c3eb' },
  { name: 'blue', hex: '#4073ff' },
  { name: 'grape', hex: '#884dff' },
  { name: 'violet', hex: '#af38eb' },
  { name: 'lavender', hex: '#eb96eb' },
  { name: 'magenta', hex: '#e05194' },
  { name: 'salmon', hex: '#ff8d85' },
  { name: 'charcoal', hex: '#808080' },
  { name: 'grey', hex: '#b8b8b8' },
  { name: 'taupe', hex: '#ccac93' },
];

const PROJECT_COLOR_HEX = new Map(PROJECT_COLORS.map((c) => [c.name, c.hex]));

export function projectColorHex(name: string | undefined): string {
  return (name && PROJECT_COLOR_HEX.get(name)) || 'var(--color-ink-light)';
}

export async function fetchProjects(): Promise<ApiProject[]> {
  return request('/projects');
}

export async function apiCreateProject(input: {
  name: string;
  color: string;
  parentId?: string | null;
}): Promise<ApiProject> {
  return request<ApiProject>('/projects', {
    method: 'POST',
    body: JSON.stringify(input),
  });
}

export async function apiUpdateProject(
  id: string,
  updates: Partial<Pick<ApiProject, 'name' | 'color' | 'parentId' | 'orderValue'>>,
): Promise<ApiProject> {
  return request<ApiProject>(`/projects/${id}`, {
    method: 'PATCH',
    body: JSON.stringify(updates),
  });
}

export async function apiDeleteProject(id: string): Promise<void> {
  await request<unknown>(`/projects/${id}`, { method: 'DELETE' });
}

export async function apiArchiveProject(id: string): Promise<ApiProject> {
  return request<ApiProject>(`/projects/${id}/archive`, { method: 'POST' });
}

export interface ProjectView {
  project: { id: string; name: string; color: string; isInbox: boolean };
  tasks: ApiTask[];
  projectId: string;
}

export async function fetchProjectView(id: string): Promise<ProjectView> {
  return request<ProjectView>(`/views/project/${id}`);
}

// ── Habits ───────────────────────────────────────────────────────────────────

export interface ApiHabit {
  id: string;
  name: string;
  // Sub-habits are one level deep: a habit with a parentId has no children of its own.
  parentId: string | null;
  // Sub-habits inherit their parent's group, so their own groupId is always null.
  groupId: string | null;
  orderValue: number;
  completions: string[]; // ISO dates (YYYY-MM-DD)
}

export interface ApiHabitGroup {
  id: string;
  name: string;
  orderValue: number;
}

export async function fetchHabits(): Promise<ApiHabit[]> {
  return request('/habits');
}

export async function apiCreateHabit(input: {
  name: string;
  parentId?: string | null;
  groupId?: string | null;
}): Promise<ApiHabit> {
  return request<ApiHabit>('/habits', {
    method: 'POST',
    body: JSON.stringify(input),
  });
}

export async function apiUpdateHabit(
  id: string,
  updates: { name?: string; parentId?: string | null; groupId?: string | null; orderValue?: number },
): Promise<ApiHabit> {
  return request<ApiHabit>(`/habits/${id}`, {
    method: 'PATCH',
    body: JSON.stringify(updates),
  });
}

export async function apiDeleteHabit(id: string): Promise<void> {
  await request<unknown>(`/habits/${id}`, { method: 'DELETE' });
}

// Only leaf habits accept completions. A parent's state is derived from its
// sub-habits, and the API rejects a write here for a habit that has children.
export async function apiToggleHabitCompletion(
  id: string,
  date: string,
  isCompleted: boolean,
): Promise<{ habitId: string; date: string; isCompleted: boolean }> {
  return request(`/habits/${id}/completions`, {
    method: 'PUT',
    body: JSON.stringify({ date, isCompleted }),
  });
}

export async function fetchHabitGroups(): Promise<ApiHabitGroup[]> {
  return request('/habit-groups');
}

export async function apiCreateHabitGroup(input: { name: string }): Promise<ApiHabitGroup> {
  return request<ApiHabitGroup>('/habit-groups', {
    method: 'POST',
    body: JSON.stringify(input),
  });
}

export async function apiUpdateHabitGroup(
  id: string,
  updates: { name?: string; orderValue?: number },
): Promise<ApiHabitGroup> {
  return request<ApiHabitGroup>(`/habit-groups/${id}`, {
    method: 'PATCH',
    body: JSON.stringify(updates),
  });
}

// Habits in the group are ungrouped, not deleted.
export async function apiDeleteHabitGroup(id: string): Promise<void> {
  await request<unknown>(`/habit-groups/${id}`, { method: 'DELETE' });
}
