import { isOnline, enqueueMutation, type QueuedMutationMethod } from '../utils/offlineQueue';
import { getSocketId } from '../utils/socket';

const BASE = '/api/v1';

const WRITE_METHODS: QueuedMutationMethod[] = ['POST', 'PATCH', 'PUT', 'DELETE'];

// Server sets `__Host-planner_csrf` in production, plain `planner_csrf` in
// dev (csrf.ts:9) - same cookie, same bundle ships to both, so check both
// names rather than branching on environment.
const CSRF_COOKIE_NAMES = ['__Host-planner_csrf', 'planner_csrf'];

let currentUserId: string | null = null;

export function setCurrentUserId(id: string | null): void {
  currentUserId = id;
}

export function getCurrentUserId(): string | null {
  return currentUserId;
}

function getCookie(name: string): string | undefined {
  const match = document.cookie.match(new RegExp(`(?:^|;\\s*)${name}=([^;]*)`));
  return match ? decodeURIComponent(match[1]) : undefined;
}

function getCsrfToken(): string | undefined {
  let raw: string | undefined;
  for (const name of CSRF_COOKIE_NAMES) {
    raw = getCookie(name);
    if (raw) break;
  }
  if (!raw) return undefined;
  const colonIndex = raw.lastIndexOf(':');
  return colonIndex === -1 ? raw : raw.substring(0, colonIndex);
}

function extractIdFromPath(path: string): string | undefined {
  // Routes here are always `/<collection>/<id>[/<action>]` (e.g. /tasks/:id,
  // /tasks/:id/complete, /habits/:id/completions) - the id is always the
  // second segment, never the last one (actions/sub-resources can follow it).
  const segments = path.split('/').filter(Boolean);
  return segments[1];
}

// Builds a same-shape stand-in for the REST response while offline, so
// callers (and `runOptimistic()`'s 2000ms budget) get something to work with
// immediately instead of waiting on a network call that will never resolve.
// The queued mutation itself carries the real request; once it replays
// successfully the normal publishEvent() -> Redis -> Socket.IO -> useSync
// flow is what actually reconciles state - this synthetic value is only a
// placeholder for the immediate call site, never a source of truth.
function buildSyntheticResponse<T>(
  method: QueuedMutationMethod,
  path: string,
  init: RequestInit,
  clientEntityId?: string,
): T {
  if (method === 'DELETE') {
    return undefined as T;
  }

  const parsedBody = init.body ? JSON.parse(init.body as string) : {};

  if (method === 'POST') {
    // Creation calls (e.g. POST /tasks) have no id in the path - use the
    // client-minted id generated by the caller (see `request()`) so the
    // same id is both returned here and stored on the queued mutation record
    // for later remapping once the real server id is known. Action calls on
    // an existing resource (e.g. POST /tasks/:id/complete) do have one
    // embedded in the path - reuse it instead of minting a new, unrelated id
    // that would desync from the record actually being acted on.
    return { id: parsedBody.id ?? extractIdFromPath(path) ?? clientEntityId ?? crypto.randomUUID(), ...parsedBody } as T;
  }

  // PATCH / PUT: echo the id embedded in the path plus whatever the caller
  // sent, so e.g. apiUpdateTask('/tasks/:id', patch) gets { id, ...patch }.
  const id = extractIdFromPath(path);
  return { ...(id ? { id } : {}), ...parsedBody } as T;
}

export interface ValidationDetail {
  field: string;
  message: string;
}

// Carries the whole error envelope the API returns, so callers can branch on
// `code` (EMAIL_IN_USE vs WEAK_PASSWORD vs RATE_LIMITED) and place field-level
// errors from `details`. Still an Error with a populated `message`, so the
// existing `err instanceof Error ? err.message : ...` call sites keep working.
export class ApiError extends Error {
  readonly code: string;
  readonly status: number;
  readonly details?: unknown;
  readonly retryAfterSeconds?: number;

  constructor(opts: {
    message: string;
    code: string;
    status: number;
    details?: unknown;
    retryAfterSeconds?: number;
  }) {
    super(opts.message);
    this.name = 'ApiError';
    this.code = opts.code;
    this.status = opts.status;
    this.details = opts.details;
    this.retryAfterSeconds = opts.retryAfterSeconds;
  }

  // `details` is unknown because it is whatever the server sent; this narrows
  // it to the validation shape at the one place that consumes it.
  fieldErrors(): ValidationDetail[] {
    if (!Array.isArray(this.details)) return [];
    return this.details.filter(
      (d): d is ValidationDetail =>
        typeof d === 'object' && d !== null && typeof (d as ValidationDetail).field === 'string',
    );
  }
}

async function request<T>(path: string, init: RequestInit = {}): Promise<T> {
  const method = (init.method ?? 'GET').toUpperCase() as QueuedMutationMethod;

  // Auth endpoints are never queued: logging in/out/registering requires a
  // real round trip and must fail loudly when offline, not resolve with a
  // synthetic session. Everything else that mutates app data is deferred.
  if (!path.startsWith('/auth/') && WRITE_METHODS.includes(method) && !isOnline()) {
    // Create calls (POST with no id segment in the path) mint their id here,
    // once, so the same value is both stored on the queued record (as
    // `clientEntityId`, for later remapping - see offlineQueue.remapQueuedId)
    // and returned in the synthetic response. Previously this id was
    // generated independently inside buildSyntheticResponse and never
    // persisted, so a dependent mutation queued afterwards (e.g. completing
    // or deleting the just-created record while still offline) had no way to
    // be corrected once the real server-assigned id came back from replay.
    const isCreate = method === 'POST' && !extractIdFromPath(path);
    const clientEntityId = isCreate ? crypto.randomUUID() : undefined;
    if (!currentUserId) {
      throw new Error('Cannot enqueue offline mutation without an authenticated user');
    }
    await enqueueMutation({ method, path, body: (init.body as string) ?? '', ownerUserId: currentUserId, clientEntityId });
    return buildSyntheticResponse<T>(method, path, init, clientEntityId);
  }

  const xsrfToken = getCsrfToken();
  const headers: Record<string, string> = {
    'Content-Type': 'application/json',
    ...(init.headers as Record<string, string> ?? {}),
  };
  if (xsrfToken) {
    headers['X-XSRF-TOKEN'] = xsrfToken;
  }

  // Lets the events this request causes come back naming this session, so the
  // page can tell its own work apart from another session's and skip refetching
  // over state it has already applied.
  const socketId = getSocketId();
  if (socketId) {
    headers['X-Socket-Id'] = socketId;
  }

  const res = await fetch(`${BASE}${path}`, {
    ...init,
    headers,
    credentials: 'include',
  });
  if (!res.ok) {
    const body = await res.json().catch(() => ({}));
    throw new ApiError({
      message: body?.error?.message ?? `HTTP ${res.status}`,
      code: body?.error?.code ?? 'HTTP_ERROR',
      status: res.status,
      details: body?.error?.details,
      retryAfterSeconds: body?.error?.retryAfterSeconds,
    });
  }
  return res.json() as Promise<T>;
}

export { request };

// ── Auth ─────────────────────────────────────────────────────────────────────

export interface AuthUser {
  id: string;
  email: string;
  displayName: string | null;
}

export async function apiRegister(
  email: string,
  password: string,
  displayName?: string,
): Promise<AuthUser> {
  const data = await request<{ user: AuthUser }>('/auth/register', {
    method: 'POST',
    body: JSON.stringify(displayName ? { email, password, displayName } : { email, password }),
  });
  return data.user;
}

export async function apiLogin(email: string, password: string): Promise<AuthUser> {
  const data = await request<{ user: AuthUser }>('/auth/login', {
    method: 'POST',
    body: JSON.stringify({ email, password }),
  });
  return data.user;
}

export async function apiLogout(): Promise<void> {
  await request<{ success: boolean }>('/auth/logout', { method: 'POST' });
}

export async function apiRequestPasswordReset(email: string): Promise<{ message: string }> {
  return request<{ message: string }>('/auth/reset-password', {
    method: 'POST',
    body: JSON.stringify({ email }),
  });
}

export async function apiConfirmPasswordReset(
  token: string,
  newPassword: string,
): Promise<{ success: boolean }> {
  return request<{ success: boolean }>('/auth/reset-password/confirm', {
    method: 'POST',
    body: JSON.stringify({ token, newPassword }),
  });
}

// ── Tasks ─────────────────────────────────────────────────────────────────────

export interface ApiTask {
  id: string;
  title: string;
  description?: string;
  priority: number;
  collectionId: string;
  sectionId?: string;
  parentTaskId?: string;
  dueDate?: string;
  isCompleted: boolean;
  orderValue: number;
  depth?: number;
  type: 'task' | 'note';
  createdAt?: string;
}

export interface Preferences {
  userId: string;
  timeZone: string;
  weekStart: 'sunday' | 'monday';
  theme: 'light' | 'dark' | 'system';
  notificationsEnabled: boolean;
  font: 'lora' | 'playpen' | 'hubballi';
  showDots: boolean;
  background: 'beige' | 'white';
  smallCaps: boolean;
  hideCompletedTasks: boolean;
  hideOldNotes: boolean;
}

export async function fetchInboxTasks(): Promise<{ tasks: ApiTask[]; collectionId: string | null }> {
  return request('/views/inbox');
}

export async function fetchTodayTasks(): Promise<{ overdue: ApiTask[]; today: ApiTask[] }> {
  return request('/views/today');
}

export async function fetchUpcomingTasks(): Promise<Array<{ date: string; tasks: ApiTask[] }>> {
  return request('/views/upcoming');
}

export async function fetchMonthNotes(year: number, month: number): Promise<{
  notesByDate: Record<string, ApiTask[]>;
  year: number;
  month: number;
}> {
  return request(`/views/month?year=${year}&month=${month}`);
}

export async function fetchPreferences(): Promise<Preferences> {
  return request<Preferences>('/preferences');
}

export async function apiUpdatePreferences(patch: Partial<Omit<Preferences, 'userId'>>): Promise<Preferences> {
  return request<Preferences>('/preferences', {
    method: 'PATCH',
    body: JSON.stringify(patch),
  });
}

export async function apiCreateTask(input: {
  title: string;
  priority?: number;
  collectionId?: string;
  dueDate?: string;
  parentTaskId?: string;
  depth?: number;
  type?: 'task' | 'note';
  recurrenceRule?: object | null;
}): Promise<ApiTask> {
  return request<ApiTask>('/tasks', {
    method: 'POST',
    body: JSON.stringify(input),
  });
}

export async function apiUpdateTask(
  id: string,
  updates: Partial<Pick<ApiTask, 'title' | 'priority' | 'dueDate' | 'depth' | 'type'>> & {
    parentTaskId?: string | null;
  },
): Promise<ApiTask> {
  return request<ApiTask>(`/tasks/${id}`, {
    method: 'PATCH',
    body: JSON.stringify(updates),
  });
}

export async function apiToggleTask(id: string, isCompleted: boolean): Promise<ApiTask> {
  return request<ApiTask>(`/tasks/${id}/${isCompleted ? 'complete' : 'reopen'}`, {
    method: 'POST',
  });
}

export async function apiDeleteTask(id: string): Promise<void> {
  await request<unknown>(`/tasks/${id}`, { method: 'DELETE' });
}

// ── Structural moves ───────────────────────────────────────────────────────────
//
// A move is deliberately separate from `apiUpdateTask`. Update patches a task's
// own fields; move rewrites tree position, list membership and the ordering of
// everything around it, and must do so in one transaction. The legacy
// `PATCH /tasks/:id/reorder` stays live for older clients but is unused here.

/**
 * Which hand-sorted list the target `position` counts within.
 *
 * These are independent orderings of the same task - see migration 025. A drag
 * inside a collection reorders the collection scope and leaves the day scope
 * alone, and vice versa.
 */
export type TaskOrderScope =
  | { kind: 'collection'; collectionId: string }
  | { kind: 'day'; dueDate: string };

export interface TaskMoveInput {
  /** New parent, or null to place at the top level. */
  parentTaskId: string | null;
  /** Omit to keep the task's current collection. */
  collectionId?: string;
  /** ISO YYYY-MM-DD; null clears the date. Omit to keep the current one. */
  dueDate?: string | null;
  /** The list the task lands in. */
  scope: TaskOrderScope;
  /** Zero-based index within that scope. Clamped server-side. */
  position: number;
}

export interface TaskMoveResponse {
  /** The dragged task and every descendant, with updated depth/collection/date. */
  moved: ApiTask[];
  /** Siblings in the source and target scopes whose order value shifted. */
  reordered: ApiTask[];
}

export async function apiMoveTask(id: string, input: TaskMoveInput): Promise<TaskMoveResponse> {
  return request<TaskMoveResponse>(`/tasks/${id}/move`, {
    method: 'PATCH',
    body: JSON.stringify(input),
  });
}

// ── Collections ────────────────────────────────────────────────────────────────

export interface ApiCollection {
  id: string;
  userId: string;
  parentId: string | null;
  name: string;
  color: string;
  isInbox: boolean;
  isArchived: boolean;
  orderValue: number;
  createdAt: string;
  updatedAt: string;
}

export const PALETTE_COLORS: ReadonlyArray<{ name: string; hex: string }> = [
  { name: 'berry_red', hex: '#b8255f' },
  { name: 'red', hex: '#db4035' },
  { name: 'orange', hex: '#ff9933' },
  { name: 'yellow', hex: '#fad000' },
  { name: 'olive_green', hex: '#afb83b' },
  { name: 'lime_green', hex: '#7ecc49' },
  { name: 'green', hex: '#299438' },
  { name: 'mint_green', hex: '#6accbc' },
  { name: 'teal', hex: '#158fad' },
  { name: 'sky_blue', hex: '#14aaf5' },
  { name: 'light_blue', hex: '#96c3eb' },
  { name: 'blue', hex: '#4073ff' },
  { name: 'grape', hex: '#884dff' },
  { name: 'violet', hex: '#af38eb' },
  { name: 'lavender', hex: '#eb96eb' },
  { name: 'magenta', hex: '#e05194' },
  { name: 'salmon', hex: '#ff8d85' },
  { name: 'charcoal', hex: '#808080' },
  { name: 'grey', hex: '#b8b8b8' },
  { name: 'taupe', hex: '#ccac93' },
];

const PALETTE_COLOR_HEX = new Map(PALETTE_COLORS.map((c) => [c.name, c.hex]));

export function paletteColorHex(name: string | undefined): string {
  return (name && PALETTE_COLOR_HEX.get(name)) || 'var(--color-ink-light)';
}

export async function fetchCollections(): Promise<ApiCollection[]> {
  return request('/collections');
}

export async function apiCreateCollection(input: {
  name: string;
  color: string;
  parentId?: string | null;
}): Promise<ApiCollection> {
  return request<ApiCollection>('/collections', {
    method: 'POST',
    body: JSON.stringify(input),
  });
}

export async function apiUpdateCollection(
  id: string,
  updates: Partial<Pick<ApiCollection, 'name' | 'color' | 'parentId' | 'orderValue'>>,
): Promise<ApiCollection> {
  return request<ApiCollection>(`/collections/${id}`, {
    method: 'PATCH',
    body: JSON.stringify(updates),
  });
}

export async function apiDeleteCollection(id: string): Promise<void> {
  await request<unknown>(`/collections/${id}`, { method: 'DELETE' });
}

export async function apiArchiveCollection(id: string): Promise<ApiCollection> {
  return request<ApiCollection>(`/collections/${id}/archive`, { method: 'POST' });
}

export interface CollectionView {
  collection: { id: string; name: string; color: string; isInbox: boolean };
  tasks: ApiTask[];
  collectionId: string;
}

export async function fetchCollectionView(id: string): Promise<CollectionView> {
  return request<CollectionView>(`/views/collection/${id}`);
}

// ── Habits ───────────────────────────────────────────────────────────────────

export interface ApiHabit {
  id: string;
  name: string;
  // Sub-habits are one level deep: a habit with a parentId has no children of its own.
  parentId: string | null;
  // Sub-habits inherit their parent's group, so their own groupId is always null.
  groupId: string | null;
  orderValue: number;
  completions: string[]; // ISO dates (YYYY-MM-DD)
}

export interface ApiHabitGroup {
  id: string;
  name: string;
  icon: string | null;
  orderValue: number;
}

export interface HabitsResponse {
  habits: ApiHabit[];
  groups: ApiHabitGroup[];
}

export async function fetchHabits(): Promise<HabitsResponse> {
  return request('/habits');
}

export async function apiCreateHabit(input: {
  name: string;
  parentId?: string | null;
  groupId?: string | null;
}): Promise<ApiHabit> {
  return request<ApiHabit>('/habits', {
    method: 'POST',
    body: JSON.stringify(input),
  });
}

export async function apiUpdateHabit(
  id: string,
  updates: { name?: string; parentId?: string | null; groupId?: string | null; orderValue?: number },
): Promise<ApiHabit> {
  return request<ApiHabit>(`/habits/${id}`, {
    method: 'PATCH',
    body: JSON.stringify(updates),
  });
}

export async function apiDeleteHabit(id: string): Promise<void> {
  await request<unknown>(`/habits/${id}`, { method: 'DELETE' });
}

// Only leaf habits accept completions. A parent's state is derived from its
// sub-habits, and the API rejects a write here for a habit that has children.
export async function apiToggleHabitCompletion(
  id: string,
  date: string,
  isCompleted: boolean,
): Promise<{ habitId: string; date: string; isCompleted: boolean }> {
  return request(`/habits/${id}/completions`, {
    method: 'PUT',
    body: JSON.stringify({ date, isCompleted }),
  });
}

export async function fetchHabitGroups(): Promise<ApiHabitGroup[]> {
  return request('/habit-groups');
}

export async function apiCreateHabitGroup(input: { name: string }): Promise<ApiHabitGroup> {
  return request<ApiHabitGroup>('/habit-groups', {
    method: 'POST',
    body: JSON.stringify(input),
  });
}

export async function apiUpdateHabitGroup(
  id: string,
  updates: { name?: string; icon?: string | null; orderValue?: number },
): Promise<ApiHabitGroup> {
  return request<ApiHabitGroup>(`/habit-groups/${id}`, {
    method: 'PATCH',
    body: JSON.stringify(updates),
  });
}

// Habits in the group are ungrouped, not deleted.
export async function apiDeleteHabitGroup(id: string): Promise<void> {
  await request<unknown>(`/habit-groups/${id}`, { method: 'DELETE' });
}

// ── Habit structural moves ─────────────────────────────────────────────────────

export interface HabitMoveInput {
  /**
   * New parent, or null to sit as a root. A habit that has children cannot take
   * a parent - the hierarchy is only one level deep.
   */
  parentId: string | null;
  /**
   * New group, or null for ungrouped. Must be null when `parentId` is set: a
   * sub-habit inherits its parent's group.
   */
  groupId: string | null;
  /** Zero-based index among the habits sharing the target parent/group scope. */
  position: number;
}

export interface HabitMoveResponse {
  /** The moved habit plus any children carried along with it. */
  moved: ApiHabit[];
  /** Every other habit whose parent, group or order value changed. */
  reordered: ApiHabit[];
}

export async function apiMoveHabit(id: string, input: HabitMoveInput): Promise<HabitMoveResponse> {
  return request<HabitMoveResponse>(`/habits/${id}/move`, {
    method: 'PATCH',
    body: JSON.stringify(input),
  });
}

export interface HabitGroupMoveInput {
  /** Zero-based index among the user's groups. */
  position: number;
}

export interface HabitGroupMoveResponse {
  /** Every group whose order value changed, including the moved one. */
  reordered: ApiHabitGroup[];
}

export async function apiMoveHabitGroup(
  id: string,
  input: HabitGroupMoveInput,
): Promise<HabitGroupMoveResponse> {
  return request<HabitGroupMoveResponse>(`/habit-groups/${id}/move`, {
    method: 'PATCH',
    body: JSON.stringify(input),
  });
}
