export type PhraseSection = 'daily' | 'inbox' | 'habits' | 'upcoming' | 'monthly';

const PHRASES: Record<PhraseSection, string[]> = {
  daily: [
    'Small, honest work — done today, done well.',
    'The day is short. The effort is yours to spend.',
    'Dignity lives in the work nobody sees.',
    'Show up. Cross one line through one thing.',
    'Today is the only day you can actually finish.',
    'Quiet hours, kept promises.',
    'Begin before you feel ready.',
    'Effort compounds. Sloth compounds too.',
    'Make a small thing real.',
    'Discipline is freedom on a leash you chose.',
    'The work returns the favor — eventually.',
    'No grand plans. Just the next clean move.',
    'A focused hour beats a frantic afternoon.',
    'Done is a kind of dignity.',
    'You are what your mornings repeat.',
    'Pick the thing that scares you, then start.',
    'Each task is a vote for who you are becoming.',
    'Slow is smooth. Smooth is finished.',
    'You owe the day one honest pass.',
    'Today, leave something better than you found it.',
  ],
  inbox: [
    'Dump it here. Sort it later.',
    'An empty head thinks more clearly.',
    'If it lives in your mind, it weighs something.',
    'Capture now — judge afterwards.',
    'Half-formed thoughts deserve a home too.',
    'Write it down before it writes you.',
    'The inbox is a parking lot, not a destination.',
    'Free the mind. Trust the list.',
    'No idea is too small to catch.',
    'Today’s noise is tomorrow’s signal.',
    'Externalize, then prioritize.',
    'Better on paper than in the back of your skull.',
    'Drop it here. The future you will sort it out.',
    'Thoughts feel heavier than they look.',
    'Catch sparks before they fade.',
    'Out of the head, into the light.',
    'A brain dump is a small act of self-respect.',
    'Hold nothing. Trust the system.',
    'The page is patient. Use it.',
    'Whisper your worries to the list.',
  ],
  habits: [
    'A streak is a promise you keep to yourself.',
    'Small reps build large lives.',
    'Skip one day, the chain reminds you who you are.',
    'You don’t rise to your goals. You fall to your habits.',
    'Boring done daily beats brilliant done once.',
    'Identity is the residue of repetition.',
    'The dot grows quietly into a person.',
    'Routine is the architecture of becoming.',
    'Every kept promise is a vote for the future you.',
    'Habits are interest paid forward.',
    'Show up on the days you don’t want to.',
    'Consistency over intensity, every time.',
    'The chain you protect protects you.',
    'No streak survives without the boring day.',
    'You become what you repeat without thinking.',
    'A habit is a decision made once, kept many times.',
    'Discipline shows up before motivation arrives.',
    'Don’t break the chain — even by an inch.',
    'Repeat until it feels like nothing. Then keep going.',
    'The quiet days are where character is built.',
  ],
  upcoming: [
    'The future is a draft. Sketch it lightly.',
    'Plan loosely. Live closely.',
    'Tomorrow listens to today.',
    'Look ahead, but don’t move in.',
    'The week is a shape — give it a frame.',
    'A calendar is a contract with future-you.',
    'See the week before it sees you.',
    'Decide once, execute many times.',
    'Tomorrow has its own weather. Pack lightly.',
    'Imagine the week as already kept.',
    'Forecasts beat regrets.',
    'Mark the rocks. Let the sand fall around them.',
    'Schedule the work — then defend it.',
    'A horizon is just a string of present moments.',
    'Plan the days, then live one at a time.',
    'Tomorrow is the cheapest place to put hard things.',
    'Whatever you don’t schedule, life will.',
    'Choose the future before it chooses you.',
    'The week deserves a thesis, not a wish.',
    'See it. Shape it. Show up.',
  ],
  monthly: [
    'The month is a map. Trace your own route.',
    'See the whole path before you take the next step.',
    'A wide view makes the next move obvious.',
    'Your life is a line — hold the pen steady.',
    'Control the calendar, control the current.',
    'Step back. The pattern reveals itself.',
    'The bird sees what the ant cannot.',
    'Zoom out. The noise becomes a shape.',
    'Your future is drawn one month at a time.',
    'Hold the whole month in your hands.',
    'A month is long enough to change direction.',
    'The horizon belongs to those who look.',
    'See the arc. Then shape it.',
    'Your path is clearer when you stop staring at your feet.',
    'The month deserves a glance, not a glance-away.',
    'Everything fits when you give it room.',
    'A life examined is a life directed.',
    'Lay the days out. Read them like a letter to yourself.',
    'The view from here is the one you chose.',
    'One page. Thirty days. Yours to steer.',
  ],
};

export function getPhrase(section: PhraseSection): string {
  const list = PHRASES[section];
  return list[Math.floor(Math.random() * list.length)];
}
