"""Generate Planner's favicon, PWA icons, in-app logos and iOS launch images.

Source: source/launchericon-512x512.png (PWABuilder Image Generator, transparent).
Launch-image devices, media queries and notebook heights come from the
Progressier generator (source/progressier-readme.txt); only its white fill is
replaced by the app's cream so launch does not flash white before the app paints.

Usage: python3 generate.py   (needs Pillow; writes into app/public and app/index.html)
"""

from pathlib import Path

from PIL import Image

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[2]
PUBLIC = REPO / "app" / "public"
INDEX_HTML = REPO / "app" / "index.html"
MASTER = HERE / "source" / "launchericon-512x512.png"

CREAM = (0xF5, 0xF0, 0xE8, 255)

# (device-width, device-height, dpr, notebook height in px, devices).
# Notebook heights are measured from Progressier's output for each device.
# Progressier's two "iPhone Duo" entries are left out: no such device ships.
IOS_DEVICES = [
    (440, 956, 3, 350, "iPhone 16 Pro Max, 17 Pro Max"),
    (402, 874, 3, 320, "iPhone 16 Pro, 17, 17 Pro"),
    (420, 912, 3, 334, "iPhone Air"),
    (430, 932, 3, 341, "iPhone 14 Pro Max, 15 Plus, 15 Pro Max, 16 Plus"),
    (393, 852, 3, 313, "iPhone 14 Pro, 15, 15 Pro, 16"),
    (428, 926, 3, 340, "iPhone 12 Pro Max, 13 Pro Max, 14 Plus"),
    (390, 844, 3, 309, "iPhone 12, 12 Pro, 13, 13 Pro, 14, 16e, 17e"),
    (375, 812, 3, 298, "iPhone X, XS, 11 Pro, 12 mini, 13 mini"),
    (414, 896, 3, 329, "iPhone XS Max, 11 Pro Max"),
    (414, 896, 2, 219, "iPhone XR, 11"),
    (414, 736, 3, 270, "iPhone 6 Plus, 6s Plus, 7 Plus, 8 Plus"),
    (375, 667, 2, 164, "iPhone 6, 6s, 7, 8, SE 2nd/3rd gen"),
    (320, 568, 2, 139, "iPhone SE 1st gen, iPod touch"),
    (1032, 1376, 2, 337, 'iPad Pro 13" M4'),
    (1024, 1366, 2, 333, 'iPad Pro 12.9"'),
    (834, 1210, 2, 296, 'iPad Pro 11" M4'),
    (834, 1194, 2, 292, 'iPad Pro 11", iPad Pro 10.5"'),
    (820, 1180, 2, 288, 'iPad Air 10.9", iPad 10th gen'),
    (834, 1112, 2, 272, 'iPad Air 10.5"'),
    (810, 1080, 2, 263, 'iPad 10.2"'),
    (768, 1024, 2, 251, 'iPad 9.7", iPad mini 7.9"'),
    (744, 1133, 2, 276, 'iPad mini 8.3"'),
]

START_MARK = "<!-- apple-touch-startup-image:start (generated by .specs/2026-09-26-app-icons-splash/assets/generate.py) -->"
END_MARK = "<!-- apple-touch-startup-image:end -->"


def notebook() -> Image.Image:
    im = Image.open(MASTER).convert("RGBA")
    return im.crop(im.getchannel("A").getbbox())


def fit(src: Image.Image, max_w: int, max_h: int) -> Image.Image:
    scale = min(max_w / src.width, max_h / src.height)
    size = (max(1, round(src.width * scale)), max(1, round(src.height * scale)))
    # Resize premultiplied so the transparent edge does not pick up dark fringes.
    return src.convert("RGBa").resize(size, Image.LANCZOS).convert("RGBA")


def canvas(w: int, h: int, art: Image.Image, fill=None) -> Image.Image:
    out = Image.new("RGBA", (w, h), fill or (0, 0, 0, 0))
    out.alpha_composite(art, ((w - art.width) // 2, (h - art.height) // 2))
    return out


def save(im: Image.Image, rel: str, opaque: bool = False) -> None:
    path = PUBLIC / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    (im.convert("RGB") if opaque else im).save(path, optimize=True)
    print(f"{rel:48s} {im.width}x{im.height}")


def square(nb: Image.Image, size: int, height_ratio: float, fill=None) -> Image.Image:
    art = fit(nb, size, round(size * height_ratio))
    return canvas(size, size, art, fill)


def main() -> None:
    nb = notebook()

    favicon_sizes = [16, 32, 48]
    favicons = [square(nb, s, 1.0) for s in favicon_sizes]
    ico = PUBLIC / "favicon.ico"
    favicons[-1].save(ico, sizes=[(s, s) for s in favicon_sizes], append_images=favicons[:-1])
    print(f"{'favicon.ico':48s} {'+'.join(map(str, favicon_sizes))}")

    save(favicons[1], "images/icons/icon-32x32.png")
    # "any" icons keep the vendor framing (notebook at 86% height, transparent).
    save(square(nb, 192, 0.86), "images/icons/icon-192x192.png")
    save(square(nb, 512, 0.86), "images/icons/icon-512x512.png")
    # iOS fills transparent pixels with black, so the touch icon is opaque cream.
    save(square(nb, 180, 0.80, CREAM), "images/icons/apple-touch-icon-180x180.png", opaque=True)
    # 62% height keeps the notebook corners inside the maskable 80% safe-zone circle.
    save(square(nb, 192, 0.62, CREAM), "images/icons/icon-maskable-192x192.png", opaque=True)
    save(square(nb, 512, 0.62, CREAM), "images/icons/icon-maskable-512x512.png", opaque=True)

    for w, h in [(16, 16), (32, 32), (28, 38), (56, 76), (64, 64), (128, 128)]:
        save(canvas(w, h, fit(nb, w, h)), f"images/logo/logo-{w}x{h}.png")

    links = []
    for dw, dh, dpr, nb_h, devices in IOS_DEVICES:
        art = fit(nb, nb.width, nb_h)
        links.append(f"  <!-- {devices} -->")
        for orientation, (w, h) in (("portrait", (dw * dpr, dh * dpr)), ("landscape", (dh * dpr, dw * dpr))):
            rel = f"images/splash/ios/apple-splash-{w}x{h}.png"
            save(canvas(w, h, art, CREAM), rel, opaque=True)
            links.append(
                f'  <link rel="apple-touch-startup-image" media="screen and (device-width: {dw}px) and '
                f"(device-height: {dh}px) and (-webkit-device-pixel-ratio: {dpr}) and "
                f'(orientation: {orientation})" href="/{rel}">'
            )

    html = INDEX_HTML.read_text()
    start, end = html.index(START_MARK), html.index(END_MARK)
    INDEX_HTML.write_text(html[: start + len(START_MARK)] + "\n" + "\n".join(links) + "\n  " + html[end:])
    print(f"index.html: {2 * len(IOS_DEVICES)} startup-image links")


if __name__ == "__main__":
    main()
